kind = "web"
previewPath = "/"
title = "Brute Pawa"
version = "1.0.0"
id = "artifacts/fblite"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = ["/"]
localPort = 22853

[services.development]
run = "pnpm --filter @workspace/fblite run dev"

[services.production]
build = ["pnpm", "--filter", "@workspace/fblite", "run", "build"]
publicDir = "artifacts/fblite/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22853"
BASE_PATH = "/"

[[services]]
name = "api-server"
paths = ["/api"]
localPort = 8080

[services.development]
run = "pnpm --filter @workspace/api-server run dev"

[services.production]
build = ["pnpm", "--filter", "@workspace/api-server", "run", "build"]
run = ["pnpm", "--filter", "@workspace/api-server", "run", "start"]

[services.env]
PORT = "8080"
