import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import walletRouter from "./wallet";
import tontinesRouter from "./tontines";
import marketplaceRouter from "./marketplace";
import jobsRouter from "./jobs";
import educationRouter from "./education";
import socialRouter from "./social";
import adminRouter from "./admin";
import uploadRouter from "./upload";
import streamRouter from "./stream";
import giftsRouter from "./gifts";
import tokensRouter from "./tokens";
import creatorRouter from "./creator";
import communityRouter from "./community";
import groupBotsRouter from "./groupBots";
import signalingRouter from "./signaling";
import pushRouter from "./push";
import storageRouter from "./storage";
import eventsRouter from "./events";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(walletRouter);
router.use(tontinesRouter);
router.use(marketplaceRouter);
router.use(jobsRouter);
router.use(educationRouter);
router.use(socialRouter);
router.use(adminRouter);
router.use(uploadRouter);
router.use(streamRouter);
router.use(giftsRouter);
router.use(tokensRouter);
router.use(creatorRouter);
router.use(communityRouter);
router.use(groupBotsRouter);
router.use(signalingRouter);
router.use(pushRouter);
router.use(storageRouter);
router.use(eventsRouter);

export default router;
