const colors = {
  light: {
    text: "#1C1E21",
    tint: "#1877F2",
    background: "#F0F2F5",
    foreground: "#1C1E21",
    card: "#FFFFFF",
    cardForeground: "#1C1E21",
    primary: "#22C55E",
    primaryForeground: "#FFFFFF",
    secondary: "#DCFCE7",
    secondaryForeground: "#16A34A",
    muted: "#DCFCE7",
    mutedForeground: "#65676B",
    accent: "#16A34A",
    accentForeground: "#FFFFFF",
    destructive: "#E41E3F",
    destructiveForeground: "#FFFFFF",
    border: "#CED0D4",
    input: "#CED0D4",
    surface: "#FFFFFF",
    divider: "#DADDE1",
  },
  dark: {
    text: "#E4E6EB",
    tint: "#2D88FF",
    background: "#18191A",
    foreground: "#E4E6EB",
    card: "#242526",
    cardForeground: "#E4E6EB",
    primary: "#2D88FF",
    primaryForeground: "#FFFFFF",
    secondary: "#3A3B3C",
    secondaryForeground: "#E4E6EB",
    muted: "#3A3B3C",
    mutedForeground: "#B0B3B8",
    accent: "#42B72A",
    accentForeground: "#FFFFFF",
    destructive: "#E41E3F",
    destructiveForeground: "#FFFFFF",
    border: "#3E4042",
    input: "#3E4042",
    surface: "#242526",
    divider: "#3E4042",
  },
  radius: 8,
};

export default colors;
