/* ═══════════════════════════════════════════════════════════════════════════
   WORLD DATA — villes, musique, langues pour les suggestions de profil
   Organisé pays par pays, région par région.
═══════════════════════════════════════════════════════════════════════════ */

export const WORLD_CITIES: string[] = [
  "Abidjan","Bouaké","Daloa","San-Pédro","Korhogo","Yamoussoukro","Man","Gagnoa",
  "Divo","Abengourou","Bondoukou","Duekoué","Soubré","Ferké","Odienné","Toumodi",
  "Agnibilékrou","Tiassalé","Lakota","Tabou","Grand-Bassam","Jacqueville","Bassam","Anyama",
  "Bingerville","Cocody","Abobo","Yopougon","Marcory","Treichville","Dakar","Thiès",
  "Kaolack","Saint-Louis","Ziguinchor","Touba","Diourbel","Tambacounda","Kolda","Sédhiou",
  "Mbour","Louga","Fatick","Kaffrine","Matam","Kédougou","Rufisque","Pikine",
  "Guédiawaye","Bargny","Joal-Fadiout","Tivaouane","Mbacké","Linguère","Podor","Bakel",
  "Tamba","Vélingara","Oussouye","Accra","Kumasi","Tamale","Sekondi-Takoradi","Cape Coast",
  "Obuasi","Koforidua","Sunyani","Ho","Wa","Bolgatanga","Techiman","Ejura",
  "Hohoe","Keta","Aflao","Tema","Ashaiman","Madina","Kasoa","Agbogbloshie",
  "Dunkwa","Nkawkaw","Kintampo","Lagos","Abuja","Kano","Ibadan","Port Harcourt",
  "Benin City","Kaduna","Maiduguri","Zaria","Aba","Jos","Ilorin","Oyo",
  "Enugu","Abeokuta","Onitsha","Warri","Sokoto","Calabar","Uyo","Asaba",
  "Awka","Makurdi","Minna","Bauchi","Gombe","Lafia","Jalingo","Owerri",
  "Orlu","Nsukka","Umuahia","Afikpo","Ogoja","Ikeja","Surulere","Victoria Island",
  "Lekki","Mushin","Agege","Oshodi","Apapa","Gbagada","Maryland","Yaba",
  "Akure","Ondo","Ilesa","Ife","Ede","Ogbomoso","Osogbo","Iwo",
  "Shaki","Sango Ota","Sagamu","Ijebu-Ode","Cotonou","Porto-Novo","Parakou","Djougou",
  "Bohicon","Kandi","Ouidah","Abomey","Natitingou","Lokossa","Aplahoué","Kétou",
  "Pobé","Sakété","Allada","Akpro-Missérété","Dogbo","Comè","Grand-Popo","Nikki",
  "Bembereke","Péhunco","Malanville","Lomé","Sokodé","Kara","Kpalimé","Atakpamé",
  "Bassar","Tsévié","Aného","Mango","Dapaong","Notsé","Vogan","Tabligbo",
  "Badou","Blitta","Sotouboua","Kanté","Niamtougou","Pagouda","Guérin-Kouka","Agbodrafo",
  "Togoville","Ouagadougou","Bobo-Dioulasso","Koudougou","Banfora","Ouahigouya","Kaya","Tenkodogo",
  "Fada N'Gourma","Dédougou","Gaoua","Manga","Ziniaré","Yako","Titao","Kongoussi",
  "Dori","Djibo","Sebba","Diébougou","Léo","Pô","Kombissiri","Zorgho",
  "Reo","Bamako","Sikasso","Ségou","Mopti","Gao","Tombouctou","Kayes",
  "Koutiala","Kidal","Bougouni","Kita","Kolondiéba","Douentza","Ténenkou","Niono",
  "Yelimané","Nioro du Sahel","Diéma","Kenieba","Bafoulabé","Kati","San","Djenné",
  "Bandiagara","Conakry","Nzérékoré","Kankan","Kindia","Labé","Guéckédou","Kissidougou",
  "Mamou","Faranah","Siguiri","Boké","Télimélé","Fria","Dalaba","Pita",
  "Koundara","Gaoual","Coyah","Forécariah","Dubréka","Boffa","Kamsar","Bissau",
  "Bafatá","Gabú","Bissorã","Bolama","Cacheu","Bubaque","Farim","Mansoa",
  "Canchungo","Buba","Quebo","Fulacunda","Bambadinca","Freetown","Bo","Kenema",
  "Makeni","Koidu","Port Loko","Magburaka","Kabala","Kailahun","Pujehun","Bonthe",
  "Moyamba","Lunsar","Waterloo","Wellington","Monrovia","Gbarnga","Kakata","Bensonville",
  "Harper","Greenville","Voinjama","Buchanan","Zwedru","Fish Town","Sanniquellie","Tubmanburg",
  "Malabo","Bata","Ebebiyín","Aconibe","Añisoc","Luba","Evinayong","Mongomo",
  "Banjul","Serekunda","Brikama","Bakau","Farafenni","Lamin","Basse","Mansakonko",
  "Janjanbureh","Kerewan","Soma","Praia","Mindelo","Santa Maria","Assomada","Pedra Badejo",
  "São Filipe","Porto Novo","Nouakchott","Nouadhibou","Rosso","Atar","Kaédi","Zouerate",
  "Kiffa","Sélibaby","Aleg","Akjoujt","Tidjikja","Néma","Ayoûn el-Atroûs","Niamey",
  "Zinder","Maradi","Tahoua","Agadez","Diffa","Dosso","Tillabéri","Arlit",
  "Birni N'Konni","Tessaoua","Mirriah","Matameye","Magaria","Aguié","Dakoro","Douala",
  "Yaoundé","Bafoussam","Garoua","Maroua","Ngaoundéré","Bertoua","Ebolowa","Kribi",
  "Bamenda","Kumba","Nkongsamba","Edéa","Limbe","Buea","Foumban","Kumbo",
  "Mbouda","Bafia","Obala","Monatélé","Tiko","Mbalmayo","Sangmélima","Dschang",
  "Loum","Melong","Bangangté","Banganté","Meiganga","Mora","Kousseri","Waza",
  "Kinshasa","Lubumbashi","Mbuji-Mayi","Kisangani","Kolwezi","Goma","Bukavu","Kananga",
  "Mwene-Ditu","Uvira","Butembo","Beni","Mbandaka","Kikwit","Matadi","Boma",
  "Tshikapa","Gandajika","Kabinda","Kongolo","Manono","Kamina","Kalemie","Bunia",
  "Dungu","Gemena","Lisala","Bandundu","Ilebo","Idiofa","Inongo","Brazzaville",
  "Pointe-Noire","Dolisie","Nkayi","Impfondo","Owando","Ouesso","Madingou","Mossendjo",
  "Kinkala","Sibiti","Djambala","Ewo","Loandjili","Bangui","Bimbo","Mbaïki",
  "Berbérati","Carnot","Bossangoa","Bambari","Bossembélé","Nola","Bouar","Bozoum",
  "Paoua","Ndélé","Bria","Bangassou","N'Djamena","Moundou","Sarh","Abéché",
  "Doba","Kélo","Pala","Am Timan","Bongor","Mongo","Bol","Faya-Largeau",
  "Koumra","Biltine","Oum Hadjer","Libreville","Port-Gentil","Franceville","Oyem","Mouila",
  "Lambaréné","Tchibanga","Makokou","Koulamoutou","Bitam","Moanda","Booué","Gamba",
  "São Tomé","Santo António","Nairobi","Mombasa","Kisumu","Nakuru","Eldoret","Thika",
  "Malindi","Nyeri","Meru","Garissa","Kakamega","Kitale","Machakos","Embu",
  "Nanyuki","Naivasha","Kericho","Kisii","Homa Bay","Migori","Bungoma","Webuye",
  "Athi River","Ruiru","Kikuyu","Limuru","Voi","Lamu","Wajir","Mandera",
  "Marsabit","Dar es Salaam","Mwanza","Arusha","Zanzibar","Dodoma","Mbeya","Tanga",
  "Morogoro","Iringa","Moshi","Kigoma","Tabora","Shinyanga","Musoma","Bukoba",
  "Sumbawanga","Lindi","Mtwara","Songea","Njombe","Singida","Babati","Korogwe",
  "Mpanda","Kampala","Gulu","Lira","Jinja","Mbarara","Fort Portal","Mbale",
  "Soroti","Arua","Masaka","Entebbe","Kasese","Kabale","Tororo","Iganga",
  "Mukono","Mityana","Masindi","Hoima","Bushenyi","Ntungamo","Isingiro","Kisoro",
  "Kigali","Butare (Huye)","Gisenyi (Rubavu)","Ruhengeri (Musanze)","Gitarama (Muhanga)","Byumba (Gicumbi)","Cyangugu (Rusizi)","Kibungo (Ngoma)",
  "Nyagatare","Rwamagana","Kayonza","Karongi","Nyamasheke","Gisagara","Nyanza","Bujumbura",
  "Gitega","Ngozi","Rumonge","Bururi","Muyinga","Kirundo","Cibitoke","Makamba",
  "Kayanza","Muramvya","Ruyigi","Cankuzo","Mwaro","Bubanza","Addis-Abeba","Dire Dawa",
  "Gondar","Mekele","Adama (Nazret)","Bahir Dar","Hawassa","Jimma","Jijiga","Shashemene",
  "Bishoftu","Sodo","Arba Minch","Hosaena","Dessie","Debre Birhan","Assosa","Gambela",
  "Nekemte","Debre Markos","Weldiya","Axoum","Lalibela","Mogadiscio","Hargeisa","Kismayo",
  "Bosaso","Baidoa","Berbera","Garowe","Burao","Merca","Belet Weyne","Galkayo",
  "Jowhar","Dhuusamarreeb","Erigavo","Borama","Djibouti","Ali Sabieh","Dikhil","Tadjourah",
  "Obock","Arta","Asmara","Keren","Massawa","Assab","Mendefera","Barentu",
  "Adi Keyh","Dekemhare","Juba","Wau","Malakal","Yei","Torit","Nimule",
  "Bor","Rumbek","Aweil","Bentiu","Khartoum","Omdurman","Port Soudan","Kassala",
  "Atbara","El Obeid","Gedaref","El Fasher","Nyala","Geneina","Wad Madani","Kosti",
  "Sennar","Dongola","Rabak","Le Caire","Gizeh","Alexandrie","Louxor","Assouan",
  "Sharm el-Sheikh","Hurghada","Port-Saïd","Suez","Ismaïlia","Mansoura","Tanta","Zagazig",
  "Asyut","Sohag","Qena","Beni Suef","Fayoum","Minya","Damanhour","Kafr el-Sheikh",
  "Banha","Shibin","Damiette","Marsa Matruh","El Arish","Siwa","Luxor","Kom Ombo",
  "Edfu","Esna","Casablanca","Rabat","Fès","Marrakech","Tanger","Agadir",
  "Meknès","Oujda","Essaouira","Tétouan","Safi","El Jadida","Beni Mellal","Khouribga",
  "Nador","Settat","Berrechid","Taza","Errachidia","Ouarzazate","Laâyoune","Dakhla",
  "Kenitra","Salé","Mohammedia","Khemisset","Khénifra","Ifrane","Azrou","Tiznit",
  "Taroudant","Guelmim","Tan-Tan","Smara","Boujdour","Alger","Oran","Constantine",
  "Annaba","Blida","Tlemcen","Sétif","Béjaïa","Batna","Tizi Ouzou","Biskra",
  "Boumerdès","El Oued","Ouargla","Ghardaïa","Médéa","Mostaganem","Msila","Mascara",
  "Skikda","Guelma","Souk Ahras","Tipaza","Khenchela","Oum el-Bouaghi","Relizane","Aïn Témouchent",
  "Naâma","Adrar","Tamanrasset","Jijel","Bordj Bou Arreridj","Bouira","Ain Defla","Aïn Beïda",
  "Chlef","Tiaret","Tunis","Sfax","Sousse","Bizerte","Hammamet","Monastir",
  "Djerba","Gabès","Kairouan","Gafsa","El Kef","Sidi Bouzid","Siliana","Zaghouan",
  "Béja","Jendouba","Nabeul","Grombalia","Menzel Bourguiba","Djerba-Houmt Souk","Tataouine","Médenine",
  "Ben Gardane","Mahdia","Kasserine","Sbeitla","Mateur","Manouba","La Marsa","Ariana",
  "Tripoli","Benghazi","Misrata","Syrte","Sabha","Tobrouk","Derna","Bayda",
  "Zaouiya","Zintan","Zinjabar","Nalut","Ghadamès","Kufra","Murzuk","Ubari",
  "Johannesburg","Le Cap","Durban","Pretoria","Port Elizabeth","Bloemfontein","East London","Pietermaritzburg",
  "Polokwane","Nelspruit","Kimberley","Rustenburg","Vanderbijlpark","Vereeniging","Soweto","Alexandra",
  "Sandton","Randburg","Centurion","Tshwane","George","Upington","Springbok","Kuruman",
  "Mthatha","Queenstown","Grahamstown","Hermanus","Stellenbosch","Paarl","Worcester","Knysna",
  "Harare","Bulawayo","Mutare","Gweru","Masvingo","Chitungwiza","Kwekwe","Kadoma",
  "Bindura","Chinhoyi","Zvishavane","Marondera","Redcliff","Chegutu","Victoria Falls","Lusaka",
  "Ndola","Kitwe","Kabwe","Livingstone","Chipata","Mufulira","Luanshya","Kasama",
  "Solwezi","Mazabuka","Mongu","Choma","Monze","Petauke","Mansa","Lilongwe",
  "Blantyre","Mzuzu","Zomba","Mangochi","Salima","Kasungu","Liwonde","Karonga",
  "Rumphi","Nkhata Bay","Nsanje","Mulanje","Thyolo","Chiradzulu","Maputo","Beira",
  "Nampula","Matola","Quelimane","Tete","Nacala","Lichinga","Pemba","Chimoio",
  "Inhambane","Maxixe","Xai-Xai","Moatize","Mocuba","Antananarivo","Toamasina","Antsirabe",
  "Mahajanga","Fianarantsoa","Toliara","Antsiranana","Nosy Be","Ambatondrazaka","Moramanga","Ambositra",
  "Morondava","Gaborone","Francistown","Maun","Serowe","Kanye","Molepolole","Selibe-Phikwe",
  "Lobatse","Palapye","Orapa","Jwaneng","Mahalapye","Kasane","Windhoek","Swakopmund",
  "Walvis Bay","Oshakati","Rundu","Katima Mulilo","Lüderitz","Keetmanshoop","Tsumeb","Outapi",
  "Otjiwarongo","Gobabis","Mariental","Mbabane","Manzini","Lobamba","Big Bend","Nhlangano",
  "Siteki","Pigg's Peak","Maseru","Teyateyaneng","Mafeteng","Mohale's Hoek","Leribe","Hlotse",
  "Butha-Buthe","Moroni","Mutsamudu","Domoni","Fomboni","Mwali","Ouani","Port-Louis",
  "Beau Bassin-Rose Hill","Vacoas-Phoenix","Curepipe","Quatre Bornes","Triolet","Goodlands","Centre de Flacq","Mahébourg",
  "Rose Belle","Flacq","Victoria","Anse Boileau","Beau Vallon","Grand Anse Mahé","Takamaka","Saint-Denis",
  "Saint-Paul","Saint-Pierre","Le Tampon","Saint-Benoît","Saint-André","Sainte-Marie","Bras-Panon","Saint-Philippe",
  "Cilaos","Hell-Bourg","Mamoudzou","Koungou","Bandraboua","Dzaoudzi","Pamandzi","Bouéni",
  "Dubaï","Abu Dhabi","Sharjah","Al Ain","Ras Al-Khaimah","Fujairah","Ajman","Umm Al-Quwain",
  "Riyad","Djeddah","La Mecque","Médine","Dammam","Taïf","Tabuk","Khobar",
  "Qatif","Hail","Buraidah","Khamis Mushait","Abha","Najran","Jizan","Al-Jubail",
  "Al-Hofuf","Yanbu","Al-Bahah","Arar","Wadi ad-Dawasir","Rafha","Sakaka","Doha",
  "Al-Wakra","Al-Khor","Al-Rayyan","Al-Shahaniya","Umm Salal","Madinat ash Shamal","Koweït","Salmiya",
  "Hawalli","Al-Ahmadi","Farwaniya","Jahra","Sabah Al-Salem","Manama","Muharraq","Riffa",
  "Hamad Town","Isa Town","Sitra","Zallaq","Mascate","Salalah","Sohar","Nizwa",
  "Sur","Ibri","Barka","Rustaq","Saham","Khasab","Sanaa","Aden",
  "Taïz","Hudaïda","Ibb","Mukalla","Dhamar","Sayoun","Al Mukha","Zinjibar",
  "Bagdad","Bassora","Erbil","Mossoul","Nadjaf","Kirkouk","Karbala","Hillah",
  "Nasiriyah","Amarah","Samawa","Diwaniyah","Ramadi","Tikrit","Falloujah","Sulaymaniyah",
  "Téhéran","Mashhad","Ispahan","Karaj","Chiraz","Tabriz","Qom","Ahvaz",
  "Kermanchah","Urmia","Rasht","Zahedan","Hamadan","Kerman","Arak","Yazd",
  "Ardabil","Bandar Abbas","Qazvin","Sanandaj","Zanjan","Khorramabad","Bojnord","Damas",
  "Alep","Homs","Lattaquié","Hama","Deir ez-Zor","Hasaké","Qamichli","Raqqa",
  "Idlib","Tartous","Soueïda","Deraa","Douma","Zabadani","Beyrouth","Saïda",
  "Tyr","Jounieh","Zahlé","Baalbek","Nabatieh","Byblos","Aley","Batroun",
  "Jbeil","Hasbaya","Marjayoun","Amman","Aqaba","Irbid","Zarqa","Madaba",
  "Jerash","Ajloun","Karak","Tafila","Ma'an","Salt","Mafraq","Ramtha",
  "Russeifa","Tel Aviv","Jérusalem","Haïfa","Beer-Sheva","Rishon LeZion","Petah Tikva","Holon",
  "Bnei Brak","Ashdod","Netanya","Bat Yam","Ramla","Herzliya","Kfar Saba","Modi'in",
  "Ramallah","Gaza","Naplouse","Hébron","Jénine","Tulkarem","Jéricho","Bethléem",
  "Istanbul","Ankara","Izmir","Bursa","Adana","Antalya","Konya","Mersin",
  "Gaziantep","Kayseri","Eskişehir","Diyarbakır","Samsun","Denizli","Malatya","Trabzon",
  "Kahramanmaraş","Erzurum","Van","Sivas","Manisa","Balıkesir","Kocaeli","Tekirdağ",
  "Sakarya","Hatay","Mumbai","Delhi","Bengaluru","Hyderabad","Chennai","Kolkata",
  "Ahmedabad","Pune","Jaipur","Surat","Lucknow","Kanpur","Nagpur","Visakhapatnam",
  "Bhopal","Indore","Patna","Vadodara","Agra","Varanasi","Rajkot","Meerut",
  "Ludhiana","Amritsar","Jabalpur","Nasik","Aurangabad","Faridabad","Ghaziabad","Noida",
  "Chandigarh","Coimbatore","Kochi","Madurai","Vijayawada","Jodhpur","Raipur","Kota",
  "Thiruvananthapuram","Guwahati","Bhubaneswar","Dehradun","Srinagar","Jammu","Shimla","Gangtok",
  "Imphal","Dispur","Aizawl","Kohima","Itanagar","Agartala","Shillong","Panaji",
  "Islamabad","Karachi","Lahore","Faisalabad","Rawalpindi","Multan","Peshawar","Quetta",
  "Sialkot","Bahawalpur","Sargodha","Gujranwala","Gujrat","Sheikhupura","Sukkur","Larkana",
  "Mirpur Khas","Rahim Yar Khan","Abbottabad","Mardan","Mingora","Nawabshah","Jacobabad","Khairpur",
  "Sadiqabad","Muzaffarabad","Dhaka","Chittagong","Sylhet","Khulna","Rajshahi","Barishal",
  "Comilla","Mymensingh","Rangpur","Bogura","Gazipur","Narayanganj","Tangail","Jashore",
  "Pabna","Faridpur","Brahmanbaria","Noakhali","Cox's Bazar","Teknaf","Colombo","Kandy",
  "Galle","Jaffna","Negombo","Trincomalee","Anuradhapura","Polonnaruwa","Batticaloa","Matara",
  "Kurunegala","Ratnapura","Nuwara Eliya","Badulla","Vavuniya","Katmandou","Pokhara","Lalitpur",
  "Biratnagar","Birgunj","Bharatpur","Janakpur","Hetauda","Dharan","Butwal","Nepalganj",
  "Dhangadhi","Tulsipur","Kaboul","Kandahar","Herat","Mazar-e-Charif","Jalalabad","Kunduz",
  "Taloqan","Lashkar Gah","Khost","Gardez","Ghazni","Fayzabad","Sheberghan","Zaranj",
  "Malé","Hulhumalé","Addu","Fuvahmulah","Kulhudhuffushi","Thimphou","Paro","Punakha",
  "Wangdue Phodrang","Mongar","Trashigang","Bangkok","Chiang Mai","Pattaya","Phuket","Khon Kaen",
  "Udon Thani","Nakhon Ratchasima","Hat Yai","Chiang Rai","Nakhon Si Thammarat","Ubon Ratchathani","Phitsanulok","Surat Thani",
  "Nonthaburi","Pak Kret","Nakhon Pathom","Samut Prakan","Rayong","Hanoï","Ho Chi Minh","Da Nang",
  "Huế","Nha Trang","Cần Thơ","Hải Phòng","Biên Hòa","Vũng Tàu","Đà Lạt","Buôn Ma Thuột",
  "Quy Nhơn","Bắc Giang","Nam Định","Thái Nguyên","Vinh","Long Xuyên","Mỹ Tho","Rạch Giá",
  "Bến Tre","Tuy Hòa","Jakarta","Surabaya","Bandung","Medan","Semarang","Makassar",
  "Palembang","Tangerang","Depok","South Tangerang","Bekasi","Bogor","Pekanbaru","Bandar Lampung",
  "Padang","Denpasar (Bali)","Malang","Yogyakarta","Mataram","Manado","Pontianak","Samarinda",
  "Banjarmasin","Balikpapan","Ambon","Jayapura","Sorong","Kupang","Palu","Kendari",
  "Kuala Lumpur","Johor Bahru","Penang (Georgetown)","Ipoh","Kota Kinabalu","Kuching","Shah Alam","Petaling Jaya",
  "Subang Jaya","Klang","Ampang Jaya","Seremban","Melaka","Alor Setar","Kota Bharu","Kuala Terengganu",
  "Miri","Sandakan","Tawau","Lahad Datu","Manille","Quezon City","Caloocan","Davao",
  "Cebu","Zamboanga","Antipolo","Taguig","Pasig","Cagayan de Oro","Valenzuela","Las Piñas",
  "Makati","Paranaque","Bacoor","General Santos","Bacolod","Iloilo","Angeles","Baguio",
  "Butuan","Mandaue","Lapu-Lapu","Singapour","Phnom Penh","Siem Reap","Sihanoukville","Battambang",
  "Kampong Cham","Pursat","Kampong Thom","Kratie","Svay Rieng","Kampot","Kep","Takeo",
  "Prey Veng","Vientiane","Luang Prabang","Pakse","Savannakhet","Thakhek","Oudomxay","Phongsali",
  "Rangoun (Yangon)","Mandalay","Naypyidaw","Bago","Mawlamyine","Taunggyi","Pathein","Sittwe",
  "Myeik","Dawei","Pyay","Meiktila","Lashio","Monywa","Hpa-An","Dili",
  "Baucau","Maliana","Suai","Ermera","Liquiçá","Viqueque","Bandar Seri Begawan","Seria",
  "Kuala Belait","Tutong","Pékin","Shanghai","Guangzhou","Shenzhen","Chengdu","Wuhan",
  "Chongqing","Tianjin","Hangzhou","Nanjing","Xi'an","Suzhou","Dongguan","Foshan",
  "Zhengzhou","Changsha","Harbin","Kunming","Qingdao","Shenyang","Xiamen","Wuxi",
  "Wenzhou","Changchun","Hefei","Taiyuan","Jinan","Fuzhou","Nanchang","Zhongshan",
  "Guiyang","Urumqi","Hohhot","Nanning","Changzhou","Zibo","Haikou","Shijiazhuang",
  "Lanzhou","Baotou","Luoyang","Tangshan","Linyi","Daqing","Jinhua","Qiqihar",
  "Anshan","Fushun","Hong Kong","Kowloon","New Territories","Macao","Taipa","Coloane",
  "Taipei","New Taipei","Taichung","Kaohsiung","Tainan","Hsinchu","Keelung","Taoyuan",
  "Changhua","Hualien","Taitung","Yilan","Zhubei","Douliu","Tokyo","Osaka",
  "Yokohama","Nagoya","Sapporo","Fukuoka","Kobe","Kyoto","Kawasaki","Saitama",
  "Hiroshima","Sendai","Kitakyushu","Chiba","Sakai","Kumamoto","Okayama","Shizuoka",
  "Hakodate","Hamamatsu","Kagoshima","Utsunomiya","Kanazawa","Naha (Okinawa)","Matsuyama","Matsumoto",
  "Nagano","Aomori","Akita","Yamagata","Séoul","Busan","Incheon","Daegu",
  "Daejeon","Gwangju","Suwon","Ulsan","Changwon","Seongnam","Goyang","Yongin",
  "Jeonju","Ansan","Cheongju","Cheonan","Namyangju","Pohang","Jeju","Gangneung",
  "Gyeongju","Iksan","Wonju","Gunsan","Mokpo","Pyongyang","Hamhung","Chongjin",
  "Nampo","Wonsan","Kaesong","Sinuiju","Hyesan","Oulan-Bator","Erdenet","Darkhan",
  "Choibalsan","Mörön","Bayanhongor","Ulaangom","Tachkent","Samarkand","Boukhara","Namangan",
  "Andijan","Navoi","Fergana","Nukus","Urganch","Jizzax","Qarshi","Termiz",
  "Navoiy","Almaliq","Almaty","Astana (Nur-Sultan)","Chymkent","Karaganda","Aktobe","Taraz",
  "Pavlodar","Ust-Kamenogorsk","Semey","Atyrau","Aktaou","Kostanay","Oral","Petropavl",
  "Bichkek","Och","Jalal-Abad","Karakol","Tokmok","Naryn","Talas","Kyzyl-Kyya",
  "Douchanbé","Khodjent","Kourgan-Tioubé","Kouliab","Qurghonteppa","Istaravshan","Achgabat","Türkmenabat",
  "Daşoguz","Mary","Balkanabat","Türkmenbaşy","Paris","Lyon","Marseille","Toulouse",
  "Nice","Nantes","Montpellier","Strasbourg","Bordeaux","Lille","Rennes","Reims",
  "Le Havre","Saint-Étienne","Toulon","Grenoble","Dijon","Angers","Nîmes","Villeurbanne",
  "Le Mans","Aix-en-Provence","Clermont-Ferrand","Brest","Tours","Amiens","Limoges","Perpignan",
  "Metz","Besançon","Caen","Orléans","Mulhouse","Rouen","Nancy","Pau",
  "Argenteuil","Montreuil","Roubaix","Tourcoing","Avignon","La Rochelle","Saint-Denis (93)","Versailles",
  "Poitiers","Dunkerque","Calais","Annecy","Chambéry","Valence","Cannes","Antibes",
  "Saint-Tropez","Monaco","Fort-de-France","Pointe-à-Pitre","Cayenne","Saint-Denis (Réunion)","Bruxelles","Anvers",
  "Gand","Charleroi","Liège","Bruges","Namur","Louvain","Mons","Aalst",
  "Mechelen","La Louvière","Sint-Niklaas","Kortrijk","Hasselt","Ostende","Amsterdam","Rotterdam",
  "La Haye","Utrecht","Eindhoven","Tilburg","Groningue","Almere","Breda","Nimègue",
  "Apeldoorn","Haarlem","Arnhem","Zaanstad","Amersfoort","Maastricht","Leiden","Dordrecht",
  "Delft","Zwolle","Venlo","Enschede","Leeuwarden","Berlin","Hambourg","Munich",
  "Cologne","Francfort","Stuttgart","Düsseldorf","Dortmund","Essen","Leipzig","Brème",
  "Dresde","Hanovre","Nuremberg","Duisbourg","Bochum","Wuppertal","Bielefeld","Bonn",
  "Mannheim","Karlsruhe","Augsbourg","Wiesbaden","Mönchengladbach","Gelsenkirchen","Aix-la-Chapelle","Braunschweig",
  "Kiel","Magdebourg","Krefeld","Freiburg","Lübeck","Oberhausen","Erfurt","Halle",
  "Kassel","Rostock","Saarbrücken","Ulm","Regensburg","Ingolstadt","Heidelberg","Zurich",
  "Genève","Bâle","Lausanne","Berne","Winterthour","Lucerne","Saint-Gall","Lugano",
  "Bienne","Thoune","Bellinzone","Coire","Schaffhouse","Frauenfeld","Vienne","Graz",
  "Linz","Salzbourg","Innsbruck","Klagenfurt","Villach","Wels","Saint-Pölten","Dornbirn",
  "Wiener Neustadt","Steyr","Bregenz","Feldkirch","Londres","Manchester","Birmingham","Liverpool",
  "Leeds","Sheffield","Bristol","Glasgow","Leicester","Edinburgh","Nottingham","Southampton",
  "Portsmouth","Brighton","Newcastle","Bradford","Cardiff","Belfast","Coventry","Sunderland",
  "Derby","Wolverhampton","Plymouth","Middlesbrough","Hull","Stoke-on-Trent","Peterborough","Swindon",
  "Luton","Reading","York","Exeter","Aberdeen","Dundee","Inverness","Dublin",
  "Cork","Limerick","Galway","Waterford","Drogheda","Dundalk","Swords","Kilkenny",
  "Tralee","Ennis","Carlow","Wexford","Sligo","Athlone","Madrid","Barcelone",
  "Séville","Saragosse","Málaga","Murcia","Palma","Las Palmas","Bilbao","Alicante",
  "Córdoba","Valladolid","Vigo","Gijón","Granada","Vitoria","La Corogne","Elche",
  "Santa Cruz de Tenerife","Oviedo","Badalona","Cartagena","Jerez de la Frontera","Sabadell","Terrassa","Alcalá de Henares",
  "Pamplona","Almería","Donostia-San Sebastián","Getafe","Hospitalet de Llobregat","Castellón","Burgos","Lisbonne",
  "Porto","Braga","Amadora","Funchal","Setúbal","Coimbra","Almada","Faro",
  "Agualva-Cacém","Queluz","Guimarães","Évora","Viseu","Leiria","Aveiro","Rome",
  "Milan","Naples","Turin","Palerme","Gênes","Bologne","Florence","Bari",
  "Catane","Venise","Vérone","Messine","Padoue","Trieste","Tarente","Brescia",
  "Prato","Modène","Reggio Calabria","Reggio Emilia","Pérouse","Parme","Livourne","Cagliari",
  "Ravenne","Foggia","Salerne","Ferrare","Rimini","Bergame","Stockholm","Göteborg",
  "Malmö","Uppsala","Västerås","Örebro","Linköping","Helsingborg","Oslo","Bergen",
  "Trondheim","Stavanger","Tromsø","Drammen","Fredrikstad","Bærum","Copenhague","Aarhus",
  "Odense","Aalborg","Esbjerg","Randers","Kolding","Horsens","Helsinki","Espoo",
  "Tampere","Vantaa","Oulu","Turku","Jyväskylä","Lahti","Reykjavik","Kópavogur",
  "Hafnarfjörður","Akureyri","Moscou","Saint-Pétersbourg","Novossibirsk","Ekaterinbourg","Kazan","Nijniy Novgorod",
  "Tchéliabinsk","Omsk","Samara","Rostov-sur-le-Don","Oufa","Krasnoïarsk","Perm","Voronej",
  "Volgograd","Krasnodar","Saratov","Tioumen","Tolyatti","Ijevsk","Barnaoul","Oulianovsk",
  "Vladivostok","Irkoutsk","Khabarovsk","Makhatchkala","Iakoutsk","Tomsk","Kiev","Kharkiv",
  "Odessa","Dnipro","Lviv","Zaporizhzhia","Mykolaïv","Marioupol","Kryvyi Rih","Vinnytsia",
  "Poltava","Tcherkassy","Tchernivtsi","Jytomyr","Soumy","Kherson","Rivne","Tchernikhiv",
  "Ivano-Frankivsk","Loutsk","Ouzhhorod","Ternopil","Varsovie","Cracovie","Łódź","Wrocław",
  "Poznań","Gdańsk","Szczecin","Katowice","Lublin","Białystok","Bydgoszcz","Sosnowiec",
  "Gdynia","Częstochowa","Radom","Toruń","Kielce","Gliwice","Zabrze","Bytom",
  "Olsztyn","Bielsko-Biała","Rzeszów","Bucarest","Cluj-Napoca","Timișoara","Iași","Craiova",
  "Constanța","Galați","Brașov","Ploiești","Brăila","Oradea","Bacău","Arad",
  "Pitești","Sibiu","Baia Mare","Buzău","Budapest","Debrecen","Miskolc","Szeged",
  "Pécs","Győr","Nyíregyháza","Kecskemét","Székesfehérvár","Szombathely","Szolnok","Tatabánya",
  "Kaposvár","Eger","Veszprém","Prague","Brno","Ostrava","Plzeň","Liberec",
  "Olomouc","Ústí nad Labem","Hradec Králové","České Budějovice","Pardubice","Zlín","Kladno","Most",
  "Opava","Frýdek-Místek","Bratislava","Košice","Prešov","Žilina","Nitra","Banská Bystrica",
  "Trnava","Martin","Sofia","Plovdiv","Varna","Burgas","Ruse","Stara Zagora",
  "Pleven","Sliven","Dobrich","Belgrade","Novi Sad","Niš","Kragujevac","Subotica",
  "Zrenjanin","Čačak","Pančevo","Kruševac","Leskovac","Užice","Vranje","Smederevo",
  "Zaječar","Valjevo","Zagreb","Split","Rijeka","Osijek","Zadar","Slavonski Brod",
  "Pula","Karlovac","Varaždin","Sarajevo","Banja Luka","Tuzla","Zenica","Mostar",
  "Bihać","Prijedor","Brčko","Tirana","Durrës","Vlorë","Elbasan","Shkodër",
  "Korçë","Fier","Berat","Gjirokastër","Athènes","Thessalonique","Patras","Héraklion",
  "Larissa","Volos","Ioannina","Kavala","Rhodes","Chania","Agrinion","Chalcis",
  "Serres","Kozani","Katerini","Trikala","Tallinn","Tartu","Narva","Pärnu",
  "Kohtla-Järve","Riga","Daugavpils","Liepāja","Jelgava","Jūrmala","Rēzekne","Valmiera",
  "Vilnius","Kaunas","Klaipėda","Šiauliai","Panevėžys","Alytus","Marijampolė","Minsk",
  "Gomel","Mohilev","Vitebsk","Grodno","Babrouïsk","Baranovitchi","Chișinău","Tiraspol",
  "Bălți","Bender","Soroca","Orhei","Ungheni","Cahul","Ljubljana","Maribor",
  "Celje","Kranj","Koper","Skopje","Bitola","Kumanovo","Tetovo","Ohrid",
  "Štip","Podgorica","Nikšić","Bar","Herceg Novi","Budva","Kotor","Pristina",
  "Prizren","Peja","Gjakova","Gjilan","Mitrovica","Tbilissi","Koutaïssi","Batoumi",
  "Roustavi","Zugdidi","Poti","Gori","Erevan","Gyumri","Vanadzor","Vagharshapat",
  "Abovian","Kapan","Bakou","Ganja","Soumgaït","Mingachevir","Lenkaran","Chirvan",
  "Nakhitchevan","New York","Los Angeles","Chicago","Houston","Phoenix","Philadelphia","San Antonio",
  "San Diego","Dallas","San José","Austin","Jacksonville","Fort Worth","Columbus","Charlotte",
  "Indianapolis","San Francisco","Seattle","Denver","Nashville","Oklahoma City","El Paso","Washington DC",
  "Las Vegas","Boston","Louisville","Portland","Memphis","Baltimore","Milwaukee","Albuquerque",
  "Tucson","Fresno","Sacramento","Kansas City","Mesa","Atlanta","Omaha","Colorado Springs",
  "Raleigh","Long Beach","Virginia Beach","Minneapolis","Tampa","New Orleans","Arlington","Bakersfield",
  "Anaheim","Aurora","Santa Ana","Corpus Christi","Riverside","St. Louis","Lexington","Pittsburgh",
  "Stockton","Anchorage","Cincinnati","St. Paul","Greensboro","Toledo","Newark","Plano",
  "Henderson","Lincoln","Buffalo","Orlando","Jersey City","Fort Wayne","Chandler","St. Petersburg",
  "Laredo","Norfolk","Madison","Durham","Lubbock","Winston-Salem","Garland","Glendale",
  "Hialeah","Reno","Baton Rouge","Irvine","Chesapeake","Irving","Scottsdale","North Las Vegas",
  "Fremont","Gilbert","San Bernardino","Rochester","Richmond","Detroit","Spokane","Des Moines",
  "Modesto","Fayetteville","Tacoma","Shreveport","Akron","Aurora (CO)","Fontana","Yonkers",
  "Glendale (AZ)","Salt Lake City","Huntington Beach","Grand Rapids","Tallahassee","Huntsville","Knoxville","Providence",
  "Brownsville","Newport News","Santa Clarita","Fort Lauderdale","Garden Grove","Oceanside","Chattanooga","Miami",
  "Oakland","Honolulu","Toronto","Montréal","Vancouver","Calgary","Edmonton","Ottawa",
  "Québec","Winnipeg","Hamilton","Kitchener","London (Ontario)","Halifax","Oshawa","Windsor",
  "Saskatoon","Regina","Barrie","Kelowna","Abbotsford","Burlington","Surrey","Brampton",
  "Mississauga","Markham","Laval","Longueuil","Gatineau","Burnaby","Richmond (BC)","Vaughan",
  "Oakville","Thunder Bay","Fredericton","Moncton","Saint John","Charlottetown","Yellowknife","Whitehorse",
  "Iqaluit","Mexico","Guadalajara","Monterrey","Puebla","Tijuana","Ciudad Juárez","León",
  "Zapopan","Mérida","Cancún","Hermosillo","Saltillo","San Luis Potosí","Aguascalientes","Mexicali",
  "Querétaro","Cuernavaca","Chihuahua","Morelia","Culiacán","Acapulco","Tuxtla Gutiérrez","Toluca",
  "Villahermosa","Tampico","Reynosa","Matamoros","Nuevo Laredo","Oaxaca","Veracruz","Jalapa",
  "Irapuato","Torreón","Durango","Tepic","Colima","Campeche","Guatemala City","Quetzaltenango",
  "Escuintla","Mixco","Villa Nueva","Petapa","San Juan","Chiquimula","Cobán","Jutiapa",
  "Huehuetenango","Chimaltenango","Tegucigalpa","San Pedro Sula","La Ceiba","El Progreso","Choluteca","Comayagua",
  "Puerto Cortés","Juticalpa","Siguatepeque","Tela","Danli","Olanchito","San Salvador","San Miguel",
  "Mejicanos","Soyapango","Apopa","Delgado","Sonsonate","Cuscatancingo","Zacatecoluca","Ahuachapán",
  "Usulután","Managua","Masaya","Matagalpa","Chinandega","Estelí","Tipitapa","Jinotega",
  "Nueva Guinea","Juigalpa","Bluefields","Puerto Cabezas","Alajuela","Desamparados","San Carlos","Heredia",
  "Cartago","Pérez Zeledón","Liberia","Puntarenas","Nicoya","Quepos","Puerto Limón","Panama City",
  "San Miguelito","Arraiján","La Chorrera","Colón","David","Santiago","Chitré","Las Tablas",
  "Aguadulce","Penonomé","Almirante","La Havane","Santiago de Cuba","Holguín","Santa Clara","Guantánamo",
  "Bayamo","Cienfuegos","Las Tunas","Camagüey","Matanzas","Pinar del Río","Sancti Spíritus","Port-au-Prince",
  "Cap-Haïtien","Gonaïves","Saint-Marc","Les Cayes","Pétion-Ville","Delmas","Carrefour","Jacmel",
  "Jérémie","Fort-Liberté","Miragoâne","Saint-Domingue","Santiago de los Caballeros","La Romana","San Pedro de Macorís","San Francisco de Macorís",
  "Puerto Plata","Higüey","Bávaro","San Cristóbal","Bayamón","Carolina","Ponce","Caguas",
  "Guaynabo","Arecibo","Toa Baja","Kingston","Montego Bay","Spanish Town","Portmore","Mandeville",
  "May Pen","Old Harbour","Port of Spain","San Fernando","Arima","Chaguanas","Point Fortin","Bridgetown",
  "Speightstown","Oistins","Bathsheba","Basse-Terre","Nassau","Saint George's (Grenade)","Roseau","Castries",
  "Kingstown","Basseterre","Saint John's (Antigua)","Gustavia","São Paulo","Rio de Janeiro","Belo Horizonte","Salvador",
  "Fortaleza","Curitiba","Manaus","Recife","Porto Alegre","Belém","Goiânia","Brasilia",
  "Campinas","São Luís","Maceió","Natal","Teresina","Campo Grande","Florianópolis","João Pessoa",
  "Santos","Ribeirão Preto","Uberlândia","Contagem","Sorocaba","Feira de Santana","Juiz de Fora","Aparecida de Goiânia",
  "Cuiabá","Joinville","Londrina","Ananindeua","Porto Velho","Serra","Macapá","Mauá",
  "São José dos Campos","Caxias do Sul","Osasco","Jaboatão dos Guararapes","Carapicuíba","Duque de Caxias","Santo André","Campina Grande",
  "Buenos Aires","Rosario","Mendoza","La Plata","Mar del Plata","San Miguel de Tucumán","Salta","Santa Fe",
  "Resistencia","Santiago del Estero","Corrientes","Posadas","Neuquén","Bahía Blanca","Paraná","Formosa",
  "Río Gallegos","Ushuaia","Comodoro Rivadavia","Bogotá","Medellín","Cali","Barranquilla","Cúcuta",
  "Bucaramanga","Pereira","Ibagué","Manizales","Santa Marta","Montería","Neiva","Armenia",
  "Villavicencio","Valledupar","Pasto","Sincelejo","Popayán","Riohacha","Quibdó","Florencia",
  "Tunja","Caracas","Maracaibo","Valencia","Barquisimeto","Maracay","Barcelona","Maturín",
  "Barinas","Cumana","Guanare","Cabimas","Lima","Arequipa","Trujillo","Chiclayo",
  "Piura","Iquitos","Cusco","Chimbote","Huancayo","Tacna","Pucallpa","Ica",
  "Juliaca","Ayacucho","Huánuco","Puno","Tarapoto","Valparaíso","Concepción","Antofagasta",
  "Viña del Mar","Temuco","Rancagua","Talca","Arica","Iquique","La Serena","Coquimbo",
  "Puerto Montt","Osorno","Punta Arenas","Quito","Guayaquil","Cuenca","Ambato","Manta",
  "Santo Domingo","Portoviejo","Machala","Esmeraldas","Loja","Ibarra","Riobamba","Babahoyo",
  "Quevedo","Latacunga","Milagro","La Paz","Cochabamba","Santa Cruz de la Sierra","Sucre","Oruro",
  "Potosí","Tarija","Trinidad","Cobija","Riberalta","Montero","Warnes","Quillacollo",
  "Sacaba","Asunción","Ciudad del Este","San Lorenzo","Luque","Capiatá","Lambaré","Fernando de la Mora",
  "Limpio","Ñemby","Pedro Juan Caballero","Encarnación","Montevideo","Salto","Paysandú","Las Piedras",
  "Rivera","Maldonado","Tacuarembó","Melo","Artigas","Minas","Florida","Young",
  "Fray Bentos","Georgetown","Linden","New Amsterdam","Anna Regina","Bartica","Corriverton","Paramaribo",
  "Lelydorp","Nieuw Nickerie","Moengo","Meerzorg","Brokopondo","Saint-Laurent-du-Maroni","Kourou","Matoury",
  "Rémire-Montjoly","Macouria","Sydney","Melbourne","Brisbane","Perth","Adelaide","Canberra",
  "Gold Coast","Wollongong","Geelong","Townsville","Cairns","Darwin","Ballarat","Bendigo",
  "Launceston","Toowoomba","Sunshine Coast","Hobart","Mackay","Rockhampton","Bundaberg","Hervey Bay",
  "Wagga Wagga","Albury","Mildura","Auckland","Christchurch","Tauranga","Napier-Hastings","Palmerston North",
  "Rotorua","Dunedin","New Plymouth","Invercargill","Nelson","Whangarei","Gisborne","Blenheim",
  "Timaru","Masterton","Port Moresby","Lae","Arawa","Mount Hagen","Madang","Wewak",
  "Goroka","Kokopo","Suva","Nadi","Lautoka","Labasa","Ba","Nasinu",
  "Sigatoka","Honiara","Gizo","Auki","Buala","Kirakira","Tulagi","Port Vila",
  "Luganville","Isangel","Sola","Apia","Vaitele","Faleasiu","Faleolo","Nuku'alofa",
  "Neiafu","Pangai","Haveluloto","South Tarawa","Betio","Bikenibeu","Funafuti","Vaiaku",
  "Palikir","Weno","Kolonia","Tofol","Majuro","Ebeye","Ngerulmud","Koror",
  "Yaren","Nouméa","Mont-Dore","Dumbéa","Paita","Bourail","Papeete","Faaa",
  "Punaauia","Mahina","Paea","Moorea","Bora Bora","Raiatea","Hagåtña","Dededo",
  "Yigo","Tamuning","Pearl City","Hilo","Kailua","Kapolei","Kaneohe",
];

/* ═══════════════════════════════════════════════════════════════════════════
   GENRES MUSICAUX — 250+ genres du monde entier
═══════════════════════════════════════════════════════════════════════════ */

export const WORLD_MUSIC_GENRES: string[] = [
  // Afrique de l'Ouest & centrale
  "Afrobeats","Afropop","Afro-fusion","Afro-soul","Afro-R&B","Afro-trap","Afro-drill","Afro-swing",
  "Coupé-Décalé","Zouglou","Zoblazo","Mapouka","Décalé","Wolosso","Gbégbé",
  "Mbalax","Sabar","Griot traditionnel","Xalam","Ngoni","Kora",
  "Highlife","Juju","Fuji","Apala","Afrobeats nigérian","Naija pop","UK Afrobeats",
  "Palmwine music","Soukous","Rumba congolaise","Ndombolo","Lingala pop",
  "Makossa","Bikutsi","Mangambeu","Assiko camerounais",
  "Kuduro","Kizomba","Semba","Tarraxinha","Ghetto zouk",
  "Kompa","Zouk","Bouyon","Soca","Calypso","Kaseko",
  "Afrohouse","Amapiano","Gqom","Shangaan electro","Mbaqanga","Isicathamiya",
  "Bongo Flava","Benga","Genge","Taarab","Ohangla","Mugithi","Ohangla",
  "Ethio-jazz","Tizita","Azmari","Funky drummer","Nubian music",
  "Raï","Chaâbi marocain","Chaâbi algérien","Staïfi","Kabyle","Gnawa","Aita",
  "Malouf","Mezwed","Nouba","Andalous","Tarab classique","Turathi",
  // Gospel / Spirituel
  "Gospel africain","Gospel américain","Gospel congolais","Louange et adoration",
  "Chant liturgique","Musique islamique","Qawwali","Nasheed","Hamdala","Zikr",
  "Gospel reggae","Gospel rap","Contemporary Christian","Hillsong","Bethel Music",
  // R&B / Soul
  "R&B","Neo-soul","Contemporary R&B","Alternative R&B","Soul classique","Nu soul",
  "Quiet storm","Funk","Groove","Disco","G-funk","Electro-soul","Bedroom pop",
  "Smooth R&B","Chill R&B","Dark R&B","New jack swing","Boogie",
  // Hip-hop / Rap
  "Hip-hop","Rap français","Rap US","Rap africain","Rap ivoirien","Rap sénégalais",
  "Rap camerounais","Rap congolais","Rap marocain","Rap algérien","Rap tunisien",
  "Drill","UK Drill","NY Drill","Chicago Drill","Brooklyn Drill","Trap",
  "Mumble rap","Conscious rap","East Coast","West Coast","Southern rap",
  "Crunk","Bounce","Hyphy","Gangsta rap","Alternative hip-hop",
  "Cloud rap","Emo rap","Lofi hip-hop","Boom bap","Jazz rap","Underground hip-hop",
  "Grime","UK garage","Bassline","UK funky","Afroswing","Roadman",
  "Phonk","Memphis rap","Drift phonk","Dark phonk",
  // Reggae / Dancehall
  "Reggae","Roots reggae","Dancehall","Bashment","Digital dancehall","Ragga",
  "Ska","Rocksteady","Lovers rock","Dub","Reggaeton","Dembow",
  "Cumbia villera","Champeta","Moombahton",
  // Pop mondiale
  "Pop","K-pop","J-pop","C-pop","Mandopop","Cantopop","Indopop","Thai pop",
  "Bollywood","Tollywood","Kollywood","Bhangra pop","Punjabi pop",
  "Latin pop","Indie pop","Electropop","Synth-pop","Dream pop",
  "Bubblegum pop","Teen pop","Art pop","Avant-pop","Power pop",
  "Kpop 4e génération","Idol pop","City pop japonaise","Shibuya-kei",
  // Électronique
  "House","Deep house","Afrohouse","Tech house","Acid house","Progressive house",
  "Electro house","Minimal house","Tribal house","Piano house","Vocal house",
  "Techno","Detroit techno","Minimal techno","Industrial techno","Berlin techno","Hard techno",
  "Trance","Progressive trance","Psytrance","Goa trance","Vocal trance","Uplifting trance",
  "Drum & Bass","Jungle","Liquid DnB","Neurofunk","Footwork","Juke",
  "EDM","Big room","Future bass","Future house","Melodic dubstep","Riddim","Brostep",
  "Ambient","Drone","Dark ambient","New age","Meditation music",
  "Chillout","Lounge","Trip-hop","Nu-jazz","Downtempo","Chillwave","Vaporwave",
  "Hyperpop","Lo-fi","Seapunk","Witch house","Nightcore","Darksynth",
  "Synthwave","Retrowave","Outrun","Cyberpunk music","Industrial",
  "EBM","Aggrotech","Futurepop","Noise","Power electronics","Glitch",
  // Jazz / Blues
  "Jazz","Bebop","Hard bop","Cool jazz","Modal jazz","Fusion jazz","Smooth jazz","Nu jazz",
  "Jazz manouche","Gypsy jazz","Latin jazz","Afro-Cuban jazz","Brazilian jazz","African jazz",
  "Blues","Delta blues","Chicago blues","Electric blues","Rhythm and blues",
  "Jump blues","Boogie-woogie","Soul blues","Texas blues","Country blues",
  // Rock et dérivés
  "Rock","Classic rock","Hard rock","Soft rock","Alternative rock","Indie rock","Garage rock",
  "Punk","Pop punk","Post-punk","Hardcore punk","Emo","Screamo","Metalcore","Post-hardcore",
  "Métal","Heavy metal","Death metal","Black metal","Thrash metal","Doom metal",
  "Nu metal","Glam metal","Progressive metal","Symphonic metal","Folk metal","Viking metal",
  "Grunge","Shoegaze","Post-rock","Prog rock","Math rock","Krautrock","Art rock",
  "Folk rock","Psychedelic rock","Space rock","Stoner rock","Desert rock",
  "Country","Country pop","Bluegrass","Americana","Folk","Singer-songwriter",
  "Indie folk","Neo-folk","Celtic folk","Appalachian music",
  // Musiques latines
  "Salsa","Bachata","Merengue","Cumbia","Vallenato","Champeta","Mapalé",
  "Sertanejo","Forró","Axé","Baile funk","Funk carioca","Pagode","Samba",
  "Bossa nova","MPB","Baião","Frevo","Maracatu","Lambada","Zouk brésilien",
  "Tango","Milonga","Vals criollo","Chicha","Huayno","Marinera","Festejo",
  "Son cubain","Guaguancó","Mambo","Cha-cha-chá","Bolero","Timba","Guaracha",
  "Reggaeton","Urbano latino","Dembow","Perreo","Trap latino",
  "Norteño","Banda sinaloense","Ranchera","Corrido","Mariachi","Cumbia pop",
  "Ska latinoamericano","Rock en español","Flamenco nuevo",
  // Musiques du monde
  "Flamenco","Fado","Tarantella","Musette","Chanson française","Schlager",
  "Celtic","Irish folk","Scottish folk","Breton folk","Nordic folk","Icelandic folk",
  "Balkan music","Rebetiko","Laïká","Sevdalinka","Tamburica","Klezmer","Polka",
  "Bhangra","Ghazal","Carnatic classique","Hindustani classique","Filmi",
  "Maqam","Mugam","Arabesk","Türkü","Taverna","Halay","Zeybek",
  "Andean music","Son jarocho","Jarabe tapatío","Huapango",
  "Gamelan","Dangdut","Keroncong","Jaipongan",
  "Enka","Visual kei","J-rock","Anisong",
  "Pansori","Trot coréen","Gugak","K-indie",
  "Guqin","Erhu","Guzheng","Peking opera","Cantopop","Mando-pop",
  // Classique & instrumental
  "Classique","Baroque","Romantique","Contemporain classique","Opéra",
  "Musique de chambre","Symphonique","Concerto","Requiem","Choral","Oratorio",
  "Musique de film","Bande originale","Neo-classical","Post-minimal","World music",
  "Ethno-jazz","Global fusion","Worldbeat","Afrofusion mondiale",
];
